twitter:
  active: false
  tweet:
    active: true
    ruleLimit: 5
    ruleLength: 512
  profile:
    active: true
    interval: 60000
  space:
    active: true
    interval: 60000
  cron:
    active: true

twitcasting:
  active: false
  live:
    active: true
    interval: 60000
  cron:
    active: true

twitch:
  active: false
  live:
    active: true
    interval: 60000
  chat:
    active: true
  cron:
    active: true

instagram:
  active: false
  track:
    active: true
    interval: 60000

tiktok:
  active: false
  proxyIndex: 0
  track:
    active: true
    interval: 300000

holodex:
  active: false
