twitter:
  active: false
  tweet:
    active: false
  profile:
    active: false
  space:
    active: false
  broadcast:
    active: false
  cron:
    active: false

twitcasting:
  active: false
  live:
    active: false
    interval: 60000
  cron:
    active: false

youtube:
  active: false
  cron:
    active: false

twitch:
  active: false
  live:
    active: false
    interval: 60000
  chat:
    active: false
  cron:
    active: false

instagram:
  active: false
  track:
    active: false
    interval: 60000

tiktok:
  active: false
  proxyIndex: 0
  track:
    active: false
    interval: 300000

holodex:
  active: false
  tweet:
    active: false
  space:
    active: false
  broadcast:
    active: false
