twitter:
  active: true
  tweet:
    active: true
    ruleLimit: 5
    ruleLength: 512
  profile:
    active: true
    interval: 60000
  space:
    active: true
    interval: 60000
  cron:
    active: true

twitcasting:
  active: true
  interval: 60000
