require('dotenv').config()

class ConfigVar {

  constructor() {
    const env = process.env
    //
    this.SETTINGS = require('../setting')
    //
    this.APP_OWNER_EMAIL_ADDRESS = env.APP_OWNER_EMAIL_ADDRESS
    this.APP_SYSTEM_EMAIL_ADDRESS = env.APP_SYSTEM_EMAIL_ADDRESS
    this.APP_SYSTEM_EMAIL_PASSWORD = env.APP_SYSTEM_EMAIL_PASSWORD
    this.APP_NOTIFICATION_DISCORD_WEBHOOK = env.APP_NOTIFICATION_DISCORD_WEBHOOK
    //
    this.DISCORD_TOKEN = env.DISCORD_TOKEN
    this.DISCORD_OWNER = env.DISCORD_OWNER || '153363129915539457'
    this.DISCORD_CLIENT_ID = env.DISCORD_CLIENT_ID || '422330233035948032'
    this.DISCORD_COMMAND_PREFIX = env.DISCORD_COMMAND_PREFIX || '.'
    this.DISCORD_COMMAND_EDITABLE_DURATION = Number(env.DISCORD_COMMAND_EDITABLE_DURATION) || 30
    this.DISCORD_NON_COMMAND_EDITABLE = getBoolean(env.DISCORD_NON_COMMAND_EDITABLE)
    this.DISCORD_UNKNOWN_COMMAND_RESPONSE = getBoolean(env.DISCORD_UNKNOWN_COMMAND_RESPONSE)
    //
    this.DISCORD_TOKEN_USER = env.DISCORD_TOKEN_USER
    //
    this.TWITTER_ENABLE = getBoolean(env.TWITTER_ENABLE)
    this.TWITTER_TWEET_ENABLE = getBoolean(env.TWITTER_TWEET_ENABLE)
    this.TWITTER_PROFILE_ENABLE = getBoolean(env.TWITTER_PROFILE_ENABLE)
    this.TWITTER_CONSUMER_KEY = env.TWITTER_CONSUMER_KEY
    this.TWITTER_CONSUMER_SECRET = env.TWITTER_CONSUMER_SECRET
    this.TWITTER_ACCESS_TOKEN = env.TWITTER_ACCESS_TOKEN
    this.TWITTER_ACCESS_TOKEN_SECRET = env.TWITTER_ACCESS_TOKEN_SECRET
    //
    this.FACEBOOK_ENABLE = getBoolean(env.FACEBOOK_ENABLE)
    this.FACEBOOK_APP_ID = env.FACEBOOK_APP_ID
    this.FACEBOOK_APP_SECRET = env.FACEBOOK_APP_SECRET
    this.FACEBOOK_ACCESS_TOKEN = env.FACEBOOK_ACCESS_TOKEN
    //
    this.CRON_ENABLE = getBoolean(env.CRON_ENABLE)
    //
    this.KCSERVERWATCHER_ENABLE = getBoolean(env.KCSERVERWATCHER_ENABLE)
    this.KCSERVERWATCHER_DISCORD_WEBHOOKS = {
      SERVER_INFO: env.KCSERVERWATCHER_DISCORD_WEBHOOK_SERVER_INFO,
      MAINT_INFO: env.KCSERVERWATCHER_DISCORD_WEBHOOK_MAINT_INFO
    }
    this.KCSERVERWATCHER_TWITTER_CONSUMER_KEY = env.KCSERVERWATCHER_TWITTER_CONSUMER_KEY
    this.KCSERVERWATCHER_TWITTER_CONSUMER_SECRET = env.KCSERVERWATCHER_TWITTER_CONSUMER_SECRET
    this.KCSERVERWATCHER_TWITTER_ACCESS_TOKEN = env.KCSERVERWATCHER_TWITTER_ACCESS_TOKEN
    this.KCSERVERWATCHER_TWITTER_ACCESS_TOKEN_SECRET = env.KCSERVERWATCHER_TWITTER_ACCESS_TOKEN_SECRET
  }

}

module.exports = new ConfigVar()

function getBoolean(value) {
  switch (value) {
    case 1:
    case '1':
    case true:
    case 'true':
      return true
  }
  return false
}
